Fix build issue
Unbabel/replicant pull request #26
Opened 2020-03-31 17:27 UTC by Gisson

Closes #25

2020-03-31 17:28 UTC, Gisson commented
@brunotm please give it a look.

2020-04-14 17:01 UTC, brunotm requested changes

2020-04-14 17:01 UTC, brunotm commented on go.mod
> +	github.com/brunotm/replicant v0.1.13
From where this dep comes from?

2020-04-14 17:01 UTC, brunotm commented on go.sum
> +github.com/brunotm/replicant v0.1.13/go.mod h1:O3s3iPuZ81RkZ+UAM/RrIiZyEhe4g0IQQL2pRnwHpjI=
same as above..

2020-09-11 08:47 UTC, brunotm commented
dup #29

2020-09-11 08:47 UTC, closed without merging